language: ruby
rvm:
  - 1.9.3
before_script:
  - mysql -e 'create database alaynamarie_test;'
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rspec spec/